export const LOANS = [
  {
    id: 'flash',
    name: 'Flash Loan',
    icon: '⚡',
    iconBg: '#E8F5EE',
    range: 'KES 3,000 – KES 15,000',
    maxAmount: 15000,
    minIncome: 5000,
    repayment: '7 – 14 days',
    interest: '8% flat',
    disbursement: 'Instant via M-Pesa',
    eligibility: 'Any registered user',
    featured: false,
    gold: false,
    example: { loan: 10000, fee: 1000 },
  },
  {
    id: 'karo',
    name: 'Karo Loan',
    icon: '🏠',
    iconBg: '#FFF9E6',
    range: 'KES 15,000 – KES 50,000',
    maxAmount: 50000,
    minIncome: 15000,
    repayment: '1 – 3 months',
    interest: '10% per month',
    disbursement: 'Within 5 minutes',
    eligibility: '30-day account history',
    featured: true,
    gold: false,
    example: { loan: 30000, fee: 3000 },
  },
  {
    id: 'biashara',
    name: 'Biashara Loan',
    icon: '📈',
    iconBg: '#E8F0FF',
    range: 'KES 50,000 – KES 150,000',
    maxAmount: 150000,
    minIncome: 40000,
    repayment: '3 – 6 months',
    interest: '12% per month',
    disbursement: 'Within 30 minutes',
    eligibility: 'Business registration',
    featured: false,
    gold: false,
    example: { loan: 100000, fee: 10000 },
  },
  {
    id: 'maisha',
    name: 'Maisha Loan',
    icon: '🏗️',
    iconBg: '#F0FFF4',
    range: 'KES 150,000 – KES 300,000',
    maxAmount: 300000,
    minIncome: 80000,
    repayment: '6 – 12 months',
    interest: '9% per month',
    disbursement: 'Same business day',
    eligibility: '6-month account history',
    featured: false,
    gold: false,
    example: { loan: 200000, fee: 20000 },
  },
  {
    id: 'premium',
    name: 'Nyota Premium',
    icon: '🌟',
    iconBg: 'rgba(255,215,0,.15)',
    range: 'KES 300,000 – KES 500,000',
    maxAmount: 500000,
    minIncome: 150000,
    repayment: '12 – 24 months',
    interest: '7% per month',
    disbursement: 'Within 24 hours',
    eligibility: '12-month history + CRB clean',
    featured: false,
    gold: true,
    example: { loan: 400000, fee: 40000 },
  },
]

export const FEE_PERCENT = 10
export const calcFee = (amount) => Math.round(amount * FEE_PERCENT / 100)
