export const LOANS = [
  {
    id: 'flash',
    name: 'Flash Loan',
    icon: '⚡',
    iconBg: '#E8F5EE',
    range: 'KES 5,000 – KES 15,000',
    maxAmount: 15000,
    minIncome: 5000,
    repayment: '7 – 14 days',
    interest: '8% flat',
    disbursement: 'Instant via M-Pesa',
    eligibility: 'Any registered user',
    featured: false,
    gold: false,
    example: { loan: 10000, fee: 1000 },
  },
  {
    id: 'karo',
    name: 'Karo Loan',
    icon: '🏠',
    iconBg: '#FFF9E6',
    range: 'KES 15,000 – KES 30,000',
    maxAmount: 30000,
    minIncome: 15000,
    repayment: '1 – 2 months',
    interest: '10% per month',
    disbursement: 'Within 5 minutes',
    eligibility: '30-day account history',
    featured: true,
    gold: false,
    example: { loan: 20000, fee: 2000 },
  },
  {
    id: 'biashara',
    name: 'Biashara Loan',
    icon: '📈',
    iconBg: '#E8F0FF',
    range: 'KES 30,000 – KES 55,000',
    maxAmount: 55000,
    minIncome: 25000,
    repayment: '2 – 3 months',
    interest: '10% per month',
    disbursement: 'Within 30 minutes',
    eligibility: 'Business registration',
    featured: false,
    gold: false,
    example: { loan: 40000, fee: 4000 },
  },
  {
    id: 'maisha',
    name: 'Maisha Loan',
    icon: '🏗️',
    iconBg: '#F0FFF4',
    range: 'KES 55,000 – KES 80,000',
    maxAmount: 80000,
    minIncome: 40000,
    repayment: '3 – 6 months',
    interest: '9% per month',
    disbursement: 'Same business day',
    eligibility: '3-month account history',
    featured: false,
    gold: false,
    example: { loan: 65000, fee: 6500 },
  },
  {
    id: 'premium',
    name: 'Zuri Premium',
    icon: '🌟',
    iconBg: 'rgba(255,215,0,.15)',
    range: 'KES 80,000 – KES 100,000',
    maxAmount: 100000,
    minIncome: 60000,
    repayment: '6 – 12 months',
    interest: '8% per month',
    disbursement: 'Within 24 hours',
    eligibility: '6-month history + CRB clean',
    featured: false,
    gold: true,
    example: { loan: 90000, fee: 9000 },
  },
]

export const FEE_PERCENT = 10
export const calcFee = (amount) => Math.round(amount * FEE_PERCENT / 100)